### ISSUE TITLE
Where is source *.tf?

### ISSUE THREAD

**Issue by ashtonian** [aws-samples/terraform-eks-workshop#1]
stumbled here through broken links from [this page](https://tf-eks-workshop.workshop.aws/500_eks-terraform-workshop/575_load_balancer/lb-controller.html), not sure if this is the right repo then but where is all the source code referenced in the demo?

**Comment by andyt530** [comment]
Hi,

Source code is here:   https://github.com/aws-samples/terraform-eks-code

**Comment by awsandy** [comment]
Source code is here: https://github.com/aws-samples/terraform-eks-code
